### PR TITLE
Update binaries to 0.12.4

### PR DESCRIPTION
**Pull request by bart-v**
Taken from http://wkhtmltopdf.org/downloads.html
Used Windows (MSVC), and extracted wkhtmltopdf.exe 32 & 64 bit versions.

### CODE REVIEW

**Comment by filipegar** [comment]
@wemersonjanuario please, merge this one! thanks.

**Comment by fkranenburg** [comment]
+1 just merge this please, thanks

**Comment by QmarXX** [comment]
+1

**Comment by nepos87** [comment]
+1

**Pull request closed without merging**
